version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pc_build
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

  pcbuildinvoice:
    image: pcbuildinvoice
    depends_on:
      - db
      - adminer
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    image: frontend
    depends_on:
      - pcbuildinvoice
    volumes:
      - ./frontend:/usr/src/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  dbdata:
