# Generated by Django 3.1.1 on 2021-12-07 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('labor', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('motherboard', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('cooler', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=100)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('case', models.CharField(blank=True, max_length=100)),
                ('fan', models.CharField(blank=True, max_length=100)),
                ('hdd', models.CharField(blank=True, max_length=100)),
                ('ssd', models.CharField(blank=True, max_length=100)),
                ('antivirus', models.BooleanField()),
                ('dust', models.BooleanField()),
                ('new_parts', models.BooleanField()),
                ('notes', models.TextField()),
                ('completed', models.BooleanField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
